# --- System & Memory ---
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_PRINTK=y

# --- Hardware Drivers ---
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_I2C_GPIO=y
CONFIG_DISPLAY=y
CONFIG_SSD1306=y

# --- Initialization Priorities ---
CONFIG_SERIAL_INIT_PRIORITY=40
CONFIG_I2C_INIT_PRIORITY=80

# --- Logging & Debug ---
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_I2C_LOG_LEVEL_DBG=y
CONFIG_GPIO_LOG_LEVEL_DBG=y
CONFIG_DISPLAY_LOG_LEVEL_DBG=y
# CONFIG_FAULT_DUMP=2
CONFIG_EXCEPTION_DEBUG=y

# --- LVGL Configuration ---
# CONFIG_LVGL=y
# CONFIG_LV_Z_MEM_POOL_SIZE=16384
# CONFIG_LV_COLOR_DEPTH_1=y
# CONFIG_LV_Z_SHELL=y
# CONFIG_LV_USE_LOG=y
# CONFIG_LV_USE_LABEL=y
# CONFIG_LV_USE_ARC=y
# CONFIG_LV_FONT_MONTSERRAT_14=y

# --- Shell ---
CONFIG_SHELL=y
CONFIG_I2C_SHELL=y