# Sistema y Kernel
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_IDLE_STACK_SIZE=1024
CONFIG_ISR_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_EVENTS=y
CONFIG_MULTITHREADING=y
CONFIG_ARM_MPU=y

# Conectividad I2C (Software GPIO)
CONFIG_I2C=y
CONFIG_I2C_GPIO=y

# Driver de Pantalla
CONFIG_DISPLAY=y
CONFIG_SSD1316=y
CONFIG_SSD1316_DEFAULT_CONTRAST=128

# Configuración de LVGL
CONFIG_LVGL=y
CONFIG_LV_Z_MEM_POOL_SIZE=65536
CONFIG_LV_Z_BUFFER_ALLOC_STATIC=y
CONFIG_LV_Z_VDB_SIZE=64
CONFIG_LV_Z_FULL_REFRESH=n
CONFIG_LV_COLOR_DEPTH_1=y
CONFIG_LV_Z_BITS_PER_PIXEL=1

CONFIG_LV_USE_THEME_DEFAULT=y
CONFIG_LV_THEME_DEFAULT_DARK=y

# Fuentes LVGL
CONFIG_LV_FONT_MONTSERRAT_8=y
CONFIG_LV_FONT_MONTSERRAT_10=y
CONFIG_LV_FONT_MONTSERRAT_16=y

# Logs y Depuración
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_I2C_LOG_LEVEL_DBG=y
CONFIG_DEBUG_OPTIMIZATIONS=y